#!/usr/bin/env python

import rospy
from std_msgs.msg import Int32


def main():
    multi_step = rospy.Publisher('~/world_control', Int32, queue_size=1)

    for i in range(10000):
        # Step simulation 1000 times
        multi_step.publish(1000)


if __name__ == '__main__':
    rospy.init_node('gazebo_tools_test')

    rospy.loginfo("STARTING")
    main()